name: CI
on: [push, pull_request]
jobs:
  tests:
    name: "Rent-to-Own Contract"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Check contract syntax"
        uses: docker://hirosystems/clarinet:latest
        with:
          args: check contracts/Rent-to-Own-Contract.clar
